version: 2

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd projects
            cd B
            
            terraform init
            terraform plan
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            cd projects
            cd B
            terraform apply -auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            cd projects
            cd B
            terraform plan -destroy
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            cd projects
            cd B
            terraform destroy -auto-approve
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply:
          filters:
            branches:
              only:
                - develop
      - hold-apply:
          type: approval
          requires:
            - plan-apply
          filters:
            branches:
              only:
                - develop
      - apply:
          requires:
            - hold-apply
          filters:
            branches:
              only:
                - develop
      - plan-destroy:
          requires:
            - apply
          filters:
            branches:
              only:
                - develop
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
          filters:
            branches:
              only:
                - develop
      - destroy:
          requires:
            - hold-destroy
          filters:
            branches:
              only:
                - develop
